---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: NeonTokyo4th-OS
description: The latest operation and maintenance system of the 4th Neon Tokyo City.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

modules:
  # Files Settings
  - type: files
    files:
      - source: system
        destination: /

  # Install default tools in system and Remove some packages
  - type: dnf 
    repos:
      nonfree: rpmfusion
      copr:
        - dejan/lazygit
    install:
      allow-erasing: true
      skip-broken: true
      packages:
      # --- Shell and Terminal ---
        - alacritty
        - fish
      # --- Terminal Tools ---
        - bat
        - zoxide
        - fastfetch
        - btop
        - htop
        - powertop
        - less
        - riggrep
        - yazi
        - wl-clipboard
        - util-linux-user
      # --- Development ---
        - neovim
        - helix
        - code
        - distrobox
        - podman-compose
        - gh
        - lazygit
      # --- Input ---
        - fcitx5
        - fcitx5-rime
      # --- Zip / Unzip ---
        - p7zip
        - p7zip-doc
        - p7zip-gui
        - p7zip-plugins
        - zstd
        - tar
        - zip
        - unzip
      # --- Useful Tools ---
        - clash-meta
      # --- System-Wide Tools ---
        - lm_sensors
        - collectd-sensors
      # --- Fonts ---
        - google-noto-fonts-all
        - wqy-zenhei-fonts
        - fontawesome-fonts-all
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: false # Send notification after install/uninstall is finished (true/false)
        scope: system
        install:
          - runtime/org.freedesktop.Platform/x86_64/25.08
          - com.google.Chrome
          - org.localsend.localsend_app
          - io.github.kukuruzka165.materialgram

  - type: systemd
    system:
      disabled:
        - flatpak-system-update.timer
      enabled:
        - clash-meta.service

  - type: os-release
    properties:
      NAME: NeonTokyo4thOS
      VERSION: Latest
      PRETTY_NAME: "NeonTokyo4th-OS"
      VARIANT: "General"
      VERIANT_ID: general
      
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
